//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppApi_quiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class participant_tb
    {
        public int participantId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> TimeSpent { get; set; }
    }
}
